name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kadekgirendra
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23FFFFFF&color_dots=%230d0d0d,%231a1a1a,%232a2a2a,%23555555,%23FFFFFF

      - name: Deploy Snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git repo

          cd repo

          if git ls-remote --exit-code --heads origin output; then
            echo "Branch output already exists"
            git checkout output
          else
            echo "Creating branch output"
            git checkout --orphan output
            git rm -rf . || true
          fi

          cp ../dist/github-contribution-grid-snake.svg .

          git add github-contribution-grid-snake.svg

          git commit -m "update contribution snake" || echo "No changes to commit"

          git push origin output
